### PR TITLE
Update api version to 2020-09-01

### PR DESCRIPTION
**Pull request by sbugalski**

### CODE REVIEW

**Comment by sbugalski** [comment]
Related to https://github.com/Azure/manage-azure-policy/issues/61

**Comment by sbugalski** [comment]
Thanks for unlocking that. Any idea why _Trigger test run_ failed?
```log
Run bash ./IntegrationTests/.github/workflows/InvokeL2RepoDispatchEvent.sh  e08789c5be03f418bcfead34e7546963cc2c2d62 Azure/manage-azure-policy 62 releases/update-api-version main            
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   388  100    90  100   298   1666   5518 --:--:-- --:--:-- --:--:--  7185
Triggering integration tests failed with: '{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}'
Error: Process completed with exit code 1.
```

**Comment by timja** [comment]
Credentials are likely not available from forks, someone with write access will need to submit it as an origin branch PR I assume

**Comment by tauhid621** [comment]
@timja is correct. We need secrets to trigger the checks. This will not work in case of fork.

**Comment by sbugalski** [comment]
Solved with https://github.com/Azure/manage-azure-policy/pull/68

**Pull request closed without merging**
